source: https://www.tensorflow.org/tutorials/quickstart/beginner

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-05-19 14:14:40.121610: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.16.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Users/bangbui/anaconda3/envs/ann1/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.6471229 , -0.2238086 , -0.28745285, -0.23809648, -0.21687746,
         0.0472528 ,  0.44420087, -0.21750322, -0.48411182, -0.42456195]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.1961973 , 0.08212063, 0.07705697, 0.08095565, 0.0826918 ,
        0.10768936, 0.16016407, 0.08264007, 0.06330004, 0.06718406]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2285047

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8565 - loss: 0.4926
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9562 - loss: 0.1537
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9681 - loss: 0.1070
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9744 - loss: 0.0851
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9776 - loss: 0.0727


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9765 - loss: 0.0738


[0.07377636432647705, 0.9764999747276306]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.43097940e-07, 3.01615177e-09, 2.15843502e-05, 1.22991958e-04,
        8.92618826e-11, 1.37011881e-07, 1.39194966e-11, 9.99841332e-01,
        3.63018529e-07, 1.30217031e-05],
       [1.26642746e-07, 1.27816616e-04, 9.99855280e-01, 1.49740818e-05,
        3.29802673e-13, 1.68345036e-06, 1.07215810e-08, 6.54761022e-13,
        8.89035547e-08, 2.03532005e-12],
       [1.15510396e-07, 9.99222398e-01, 7.75524968e-05, 9.50054891e-06,
        2.63631464e-05, 1.37883535e-05, 4.55492773e-06, 5.09313308e-04,
        1.35840062e-04, 4.43281237e-07],
       [9.99893069e-01, 1.40278567e-09, 1.02101039e-04, 5.62343727e-09,
        2.24018564e-07, 6.61956790e-07, 2.42660326e-06, 1.42916281e-06,
        4.53109017e-09, 4.63080028e-08],
       [6.80260655e-06, 5.60525777e-08, 2.04698241e-04, 1.17473337e-06,
        9.94282961e-01, 7.24726078e-07, 3.70007074e-05, 2.97925377e-04,
        4.44062880e-06, 5.16431360e-03]], dtype=float32)>