# Feedforward nerual networks

- tensorflow==2.16.1
- keras==3.3.3
- numpy == 1.26.4
- sklearn==1.4.2

In [20]:
# import tensorflow as tf
# print(tf.__version__)
import keras
print(keras.__version__)
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import sklearn
print(sklearn.__version__)
from sklearn.model_selection import train_test_split

3.3.3
1.4.2


In [21]:
data = np.random.random((1000,10))
Y = np.random.randint(2,size= (1000,1))
model = Sequential()

In [22]:
validation_size = 0.2
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(data, Y, test_size=validation_size, random_state=seed)

In [23]:
type(data)
data.dtype
print(f"data: {data}")
print(f"Y: {Y}")

data: [[0.16329477 0.28960161 0.13463676 ... 0.53961844 0.73594507 0.1765709 ]
 [0.79905946 0.96513209 0.05381323 ... 0.04562662 0.43210362 0.77474854]
 [0.02673255 0.30900764 0.62912041 ... 0.43507844 0.83044444 0.51041252]
 ...
 [0.96559654 0.75416008 0.73398764 ... 0.15867043 0.97024224 0.55669904]
 [0.89716672 0.25124112 0.86498156 ... 0.81043168 0.10400731 0.37671649]
 [0.73266093 0.96290007 0.24403698 ... 0.18229974 0.16945593 0.27701361]]
Y: [[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [

In [24]:
model = Sequential()
model.add(Dense(32, input_dim=10, activation= 'relu' ))
model.add(Dense(32, activation= 'relu' ))
model.add(Dense(1, activation= 'sigmoid'))

In [25]:
model.compile(loss= 'binary_crossentropy' , optimizer= 'adam' , metrics=[ 'accuracy' ])

In [26]:
model.fit(data, Y, epochs=10, batch_size=32)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4885 - loss: 0.6950
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5262 - loss: 0.6918
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5262 - loss: 0.6915
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5599 - loss: 0.6876 
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5425 - loss: 0.6894 
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5344 - loss: 0.6894
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5539 - loss: 0.6857
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5417 - loss: 0.6872
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5774 - loss: 0.6812 
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5360 - loss: 0.6866 


In [27]:
scores = model.evaluate(X_test, Y_test)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5618 - loss: 0.6834  
compile_metrics: 56.00%


# play around more